name: '规划'
description: '规划编译流程'
outputs:
  matrix:
    description: "matrix参数"
    value: ${{ steps.config-generator.outputs.matrix }}
strategy:
  matrix:
    include:
    - mt798x: rax3000m-emmc
    - mt798x: rax3000m-nand
    - mt798x-nousb: nokia_ea0326gmp_ubootmod
    - mt798x-nousb: nokia_ea0326gmp_stock
    - ramips: lenovo_newifi-d1
    - ramips: lenovo_newifi-y1
    - ramips: d-team_newifi-d2
runs:
  using: "composite"
  steps:
        - id: config-generator
          run: |
            matrix="["
            if [ "${{ github.event.inputs.MACH }}" == "${{ matrix.mt798x }}" ]; then
              matrix+='{"target":"mt798x-iptables",{"target":"mt798x-nftables"}'
            elif [ "${{ github.event.inputs.MACH }}" == "${{ matrix.mt798x-nousb }}" ]; then
              matrix+='{"target":"mt798x-nousb-iptables"},{"target":"mt798x-nousb-nftables"}'
            elif [ "${{ github.event.inputs.MACH }}" == "${{ matrix.ramips }}" ]; then
              matrix+='{"target":"ramips-iptables"},{"target":"ramips-nftables"}'
            fi
            matrix+="]"
            echo "Generated matrix: $matrix"
            echo "matrix=$matrix" >> $GITHUB_OUTPUT
          shell: bash
